### ISSUE TITLE
Missing fields in v2.0

### ISSUE THREAD

**Issue by jeffyoungstrom** [MrTarantula/WIPrint#7] opened 2017-08-14 19:33 UTC
I configured Task to print the following fields in the following order:

> 	Title
> 	Iteration Path
> 	Assigned To
> 	State
> 	Reason
> 	Blocked (custom String field)
> 	SLPriority (custom String field)
> 	Remaining Work
> 	Backlog Priority
> 	Activity
> 	Area Path
> 	Description

The following fields are not printing despite having contents:

> 	Iteration Path (System.IterationPath)
> 	SLPriority (custom String field)
> 	Remaining Work (Microsoft.VSTS.Scheduling.RemainingWork)
> 	Backlog Priority (Microsoft.VSTS.Common.BacklogPriority)

All other listed fields print as expected.

Bug:

> 	Title (ok)
> 	Iteration Path **(missing)**(System.IterationPath)
> 	Assigned To (ok)
> 	State (ok)
> 	Reason (ok)
> 	SLPriority **(missing)**(custom String field)
> 	Regression (ok)
> 	Effort **(missing)**(Microsoft.VSTS.Scheduling.Effort)
> 	Remaining Work **(missing)**(Microsoft.VSTS.Scheduling.RemainingWork)
> 	Activity (ok)
> 	Severity **(missing)**(Microsoft.VSTS.Common.Severity)
> 	Area Path (ok)
> 	Clinical Concern **(missing)**(custom String field)
> 	Business Concern **(missing)**(custom String field)
> 	Probability of Occurrence **(missing)**(custom String field)
> 	Risk to Product **(missing)**(custom String field)
> 	QMS ID **(missing)**(custom String field)
> 	Symptom (ok)(custom Html field)
> 	Repro Steps (ok)
> 	Found In (ok)
> 	Integration Build (ok)
> 	System Info (ok)
> 	Verification Test Cases **(missing)**(custom String field)
> 	Design Summary Package (ok)(custom String field)
> 	Deferred Comment (ok)(custom Html field)
> 	Acceptance Criteria **(missing)**(Microsoft.VSTS.Common.AcceptanceCriteria)

Doesn't seem to have anything to do with custom vs. built-in fields since some of our custom fields print fine.

I'm testing with work items that have values in all of the listed fields.

I'm still using TFS 2015 update 3.

**Comment by jeffyoungstrom** [comment] 2017-08-14 20:00
Of the multiple issues I just entered, this is the only one that is currently a show stopper for me. FYI.

**Comment by MrTarantula** [comment] 2017-08-14 20:02
I think I know what the problem is. I'm only doing simple parsing for dates and dropping things if they look close enough to an invalid date because TFS stores some "empty" date fields as 1/1/9999 and I didn't want that junk to make it through to printing. Numbers or strings that contain numbers can be loosely parsed as dates (through the wonders of JavaScript) and my script is dropping them as junk.

I just looked through the API and I can add another call to check the field type before choosing how to display it. Hopefully it won't add much overhead to rendering the pages.

In the meantime I will ease up on the date restrictions. I pushed `v2.0.1` as a workaround while I work on better field parsing. It's now in the marketplace. Thanks for the feedback.

**Comment by jeffyoungstrom** [comment] 2017-08-14 21:32
2.0.1 seems to display all the missing fields. It does feel quite a bit slower than 2.0 did. Thanks!

**Comment by MrTarantula** [comment] 2017-08-14 22:03
Good to know it's displaying better. Let me know if anything else displays wrong or strangely.

**Comment by MrTarantula** [comment] 2017-10-03 14:26
Closing this as this specific bug was fixed.

**Closed by MrTarantula** 2017-10-03 14:26 UTC
